-- 用户表
CREATE TABLE `user` (
  `userId` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '主键id',
  `name` VARCHAR(255) DEFAULT NULL COMMENT '用户名',
  `createAt` DATETIME DEFAULT NULL COMMENT '创建时间',
  `loginAt` DATETIME DEFAULT NULL COMMENT '最后登录时间',
  PRIMARY KEY (`userId`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;